name: Test and Build

on:
  push:
  pull_request:

permission:
  contents: read

jobs:
  tests:
    run-on: ubuntu-latest

    stps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Dar permisos a Gradel
        run: chmod +x gradlew

      - name: Ejecutar tests
        run: ./gradlew test
